### ISSUE TITLE
enhancement request: make WIFI configurable

### ISSUE THREAD

**Issue by tueddy** [squix78/esp8266-weather-station#13]
Hello,

nice widget/library!
Is it possible to enhance weather widget to select WIFI station and password at runtime?
Currently you have to hardcode at design-/compiletime.

Maybe with WifiManager?
Or with a rotary encoder + button to edit station/password directly on screen? So smart like on AppleTV?

Best regards
Dirk

**Comment by squix78** [comment]
Hi Dirk. Yes, both has been done in the meantime. I added a demo using the WifiManager called WeatherStationDemoExtended using the WifiManager. The rotary encoder thing has been described here: http://www.bloggingadeadhorse.com/programming_esp8266_2.php
Do you agree that we can close this issue?

**Comment by tueddy** [comment]
Hi Daniel,

in the meantime there are so many libraries & solutions for ESP8266 so it can be done easily. 
So i close this issue!
Best regards
Dirk
