### ISSUE TITLE
Exception (28) crash

### ISSUE THREAD

**Issue by squix78** [squix78/esp8266-weather-station#3]
Exception (28):
epc1=0x4000df60 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff0230 end: 3fff0920 offset: 01a0

>>>stack>>>
3fff03d0:  3ffef164 00000004 3fff096c 402075ba  
3fff03e0:  3fff25d0 00000001 3ffef338 40207612  
3fff03f0:  40106788 3ffef154 3ffef338 40207642  
3fff0400:  3ffef164 3fff0470 3ffef338 40207744  
3fff0410:  3fff25d0 3fff0470 3ffef154 402038cd  
3fff0420:  3fff2928 0000000f 00000004 3fff2908  
3fff0430:  0000000f 00000001 3fff0470 40207642  
3fff0440:  40203698 00000004 3fff0470 40207690  
3fff0450:  3fff050d 0000000f 00000000 3fff08b0  
3fff0460:  40203698 3ffef154 3fff04b0 40204353  
3fff0470:  3fff25d0 0000000f 00000001 40204591  
3fff0480:  3fff0870 ffffffdf 3fff04b0 402046b1  
3fff0490:  0000002c ffffffdf 00000022 4020512e  
3fff04a0:  0000002c 3fff096c 00000001 402041bc  
3fff04b0:  00000005 00000000 00000000 00000000  
3fff04c0:  00000001 00000000 00000000 00000003  
3fff04d0:  00000003 00000000 00000000 00000000  
3fff04e0:  00000000 00000000 00000000 00000000  
3fff04f0:  00000000 00000000 00000000 00000000  
3fff0500:  4010248a 00000006 3ffef154 6c003600  
3fff0510:  73756973 00746900 74006863 65636500  
3fff0520:  7265626d 2c303120 31303220 69670035  
3fff0530:  64750066 69672e79 6c630066 7964756f  
3fff0540:  74616c20 4c202e65 3320776f 57202e43  
3fff0550:  73646e69 67696c20 61207468 7620646e  
3fff0560:  61697261 2e656c62 202e0000 6e616843  
3fff0570:  6f206563 61722066 34206e69 002e2530  
3fff0580:  43202e00 636e6168 666f2065 69617220  
3fff0590:  3033206e 00002e25 0000007f 3ffece10  
3fff05a0:  3fff12a8 3fff2858 3fff168f 00000030  
3fff05b0:  40217670 3ffecdc0 3fff12a8 3ffecdc0  
3fff05c0:  00000002 00000000 00000020 40103afb  
3fff05d0:  00000005 00000000 0000000a 00000000  
3fff05e0:  00000005 00000000 0000000a 00000000  
3fff05f0:  00000001 00000000 0000000a 00000000  
3fff0600:  00000001 00000000 0000000a 00000000  
3fff0610:  00005000 00000000 00005000 0000a000  
3fff0620:  00000000 a0000000 00000000 0000001c  
3fff0630:  00001000 3ffece10 00001000 0000a000  
3fff0640:  40217670 00000000 00001000 3fff0693  
3fff0650:  0000a000 00000005 00000020 40001e4b  
3fff0660:  3fff0692 00000000 40001e65 3fff06b1  
3fff0670:  3fff0730 00000001 3fff2858 40001e4b  
3fff0680:  3fff06b0 00000000 00000000 00000000  
3fff0690:  40353037 3fff2892 3fff2858 3fff1660  
3fff06a0:  3fff26a8 3fff166c 3fff1660 00000002  
3fff06b0:  3fff0e31 00000003 3fff1660 4020f73d  
3fff06c0:  000000c0 0002e8e2 0000a8c0 402095c8  
3fff06d0:  3fff1660 00000000 00000000 3fff2858  
3fff06e0:  3fffd83c 40002394 00000007 ffffffff  
3fff06f0:  40001da0 00000064 00000000 0000000a  
3fff0700:  3fffd83c 40002394 00000004 00000000  
3fff0710:  00000001 00000064 00000000 0000000a  
3fff0720:  40001f46 00000006 000000ff 00000006  
3fff0730:  00000031 00000000 3fff26a8 4020963c  
3fff0740:  3fff1660 3fff2808 00000000 000000ff  
3fff0750:  00000000 3fff07c0 3fff07c0 3ffe8b17  
3fff0760:  40002514 3fffdd3c 3fff0820 0000000a  
3fff0770:  00000000 3fff07e0 3fff07e0 3ffe8ace  
3fff0780:  40002514 3fffdd3c 00000000 3ffef110  
3fff0790:  00006270 00000000 00000008 00000000  
3fff07a0:  00000000 00000001 00000000 3fff0731  
3fff07b0:  00000000 40106776 3fff0838 00000006  
3fff07c0:  3fff07e0 3fff07e0 00000004 40204e9b  
3fff07d0:  3fff1760 00000007 40205df0 3ffef900  
3fff07e0:  40205d68 3fff1760 3ffef7a0 3fff2778  
3fff07f0:  40106788 3fff087c 3fff087c 00000001  
3fff0800:  3fff2518 40106776 3fff0870 00000034  
3fff0810:  00000034 00000001 00000000 0000290f  
3fff0820:  00000000 3ffe8b60 00000000 000003e8  
3fff0830:  00000000 00000000 3fff2578 3fff28b0  
3fff0840:  0000007f 00000074 3fff25b0 0000000f  
3fff0850:  00000004 3fff08c8 3ffef154 40207768  
3fff0860:  3fff08bc 3fff08c8 3ffef154 402042ca  
3fff0870:  3fff2528 0000003f 00000034 3fff2228  
3fff0880:  0000003f 00000034 3fff08b0 40207744  
3fff0890:  00000000 00000000 3ffef154 3ffef104  
3fff08a0:  3ffef0f8 3ffef0ec 3ffef154 402028ab  
3fff08b0:  3fff2138 0000000f 00000006 3fff1938  
3fff08c0:  0000000f 00000002 3fff1760 0000001f  
3fff08d0:  00000010 00000000 00000000 40202b89  
3fff08e0:  00000000 00000000 00000016 3ffef8f0  
3fff08f0:  3fffdc20 00000000 3ffef32c 40202a1b  
3fff0900:  3fffdc20 00000000 3ffef8e8 40205e39  
3fff0910:  00000000 00000000 3ffef900 40100114  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset

Exception 28 means LoadProhibitedCause

**Comment by darkstar2002** [comment]
I have found if I switch the timeclient to use yahoo.com instead of google.com it works just fine.

**Comment by squix78** [comment]
Didn't have these issues anymore. Maybe fixed in the Arduino/ESP8266 library
