### ISSUE TITLE
Arduino IDE Keeps requesting ESP8266 Weather Station updates, but already updated

### ISSUE THREAD

**Issue by G6EJD** [squix78/esp8266-weather-station#49]
Hi Daniel,
If you use the Arduino IDE you will get a constant request to update your library from 1.1.1 to 1.1.2 and when you do update to 1.1.2 it still keeps requesting an update. It looks like something has not been set correctly in the IDE or Library Update process to signal that once the update has been completed there is no further update required.
![esp8266-weather-sta](https://cloud.githubusercontent.com/assets/6075568/21582130/17a57c06-d044-11e6-93fe-9fe39b340d1a.jpg)

**Comment by Supersimo88** [comment]
you hare not up to date, there is a versione 1.1.3, click on select versione, select the latest version and install

**Comment by G6EJD** [comment]
I'm using Arduino IDE 1.8 and it does not show 1.1.3 as an update. I can see the JSON has been updated on GitHub, but it's not being downloaded via the IDE. Maybe the Weather Station is only supported for earlier IDE versions.

**Comment by G6EJD** [comment]
Resolved, I had two versions of the ESP8266_Weather_station, removed old version, now shows 1.1.3, thanks for the hint.
