### ISSUE TITLE
support for SH1106 OLED Displays (1.3" and i2C)

### ISSUE THREAD

**Issue by tattobeck** [squix78/esp8266-weather-station#51]
Hi squix78,
I'm searching for (and haven't found yet) a way to get your Code running with those 1.3" I2C OLED Displays sold from chinese sellers on eBay.
They are slightly larger and better to read then the 0.96" Displays. 

The only problem is that most of them are sold with an SH1106-Chip which is a little different to the SSD1306 (although they say, it's compatible).
When i connect it, i get an initialized display, but the screen is flickering and there's no readable output.

as far as i know the difference is that SH1106 controller has an internal RAM of 132x64 pixel. The SSD1306 only has 128x64 pixel. First problem for standard 128x64 OLEDs with SH1106 controller is: How is the 128x64 window mapped into the 132x64 RAM? It seems, that the 128x64 OLED is centered in most cases within the 132x64 area, that means pixel (2,0) in ram is pixel (0,0) on the display. 

Has anybody managed to get the weatherstattion-code working on sh1106 displays?

maybe would you improve your code to Support SH1106-displays? they seem to be common...

Thanks a lot!

**Comment by tattobeck** [comment]
wow!
found your Website where you already adressed that issue ;)

[https://blog.squix.org/2016/08/esp8266-weather-station-on-a-big-screen.html](url)

It works!!! 
Thanks @squix78

**Comment by squix78** [comment]
Your welcome! I was just about to note that the library already supports those displays:-). Great you found it even faster by yourself!
