### ISSUE TITLE
Some questions about esp8266-weather-station

### ISSUE THREAD

**Issue by myxingchao** [squix78/esp8266-weather-station#7]
Hello, I try to build your project, but there has been compiling these contents

Arduino:1.6.5 (Windows 8.1), 板："Generic ESP8266 Module, Serial, 80 MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS), ck"

WeatherStationDemo.ino:33:33: warning: extra tokens at end of #include directive [enabled by default]
WeatherStationDemo.ino:34:34: warning: extra tokens at end of #include directive [enabled by default]
WeatherStationDemo:50: error: 'D3' was not declared in this scope
WeatherStationDemo:51: error: 'D4' was not declared in this scope
'D3' was not declared in this scope

**Comment by squix78** [comment]
Just replace d4 and d3 with the gpio pins u are using (e.g 5 or 6) for the display and it should compile

**Comment by myxingchao** [comment]
Thank you for your reply, I have compiled successfully, but the download is the emergence of a new error

warning: espcomm_sync failed
error: espcomm_open failed

**Comment by squix78** [comment]
That means your computer cannot talk to the ESP8266. The reason for this can be one of many and depends on the board. Have u put the Esp in in upload mode?

**Comment by squix78** [comment]
Will close this now, because mean issue fixed, secondary issue was related to transfer problems
