### ISSUE TITLE
Thingspeak data field returned 'null'

### ISSUE THREAD

**Issue by ConorMatthews** [squix78/esp8266-weather-station#88]
On the last slide the thingspeak data field returns 'null' when i use it.
Here is my thingspeak channel:  https://thingspeak.com/channels/336514
Help is appreciated!
Thanks

**Comment by lorol** [comment]
Do you actually write periodically your own data (from an external sensor etc.) to this channel so this data is then available for (your) reading?
The link above is to private channel, so it is pointless to show it here without giving the read access api key. No one can see the data from it :)

**Comment by ConorMatthews** [comment]
I have made this ( https://thingspeak.com/channels/340776 ) channel public, I tried making a new one but that still didn't work. I need to run the device that uploads the data so i will do that later (4:00pm GMT).
The channel id is: 340776
The read API is: P6MITCR982A3ML9D

Thanks for your time

**Comment by ConorMatthews** [comment]
I am uploading data using this code:
` #include <DHT.h>  
 #include <ESP8266WiFi.h>  
 #include <WiFiClient.h>  
 #include <ThingSpeak.h>  
 #define DHTPIN D5  
 #define DHTTYPE DHT11  
 DHT dht(DHTPIN, DHTTYPE);  
 const char* ssid = "WiFiName";  
 const char* password = "Password";  
 WiFiClient client;  
 unsigned long myChannelNumber = 174314;  
 const char * myWriteAPIKey = "JQPT38EM56K0MJM1";  
 uint8_t temperature, humidity;  
 void setup()  
 {  
  Serial.begin(115200);  
  dht.begin();  
  delay(10);  
  // Connect to WiFi network  
  Serial.println();  
  Serial.println();  
  Serial.print("Connecting to ");  
  Serial.println(ssid);  
  WiFi.begin(ssid, password);  
  while (WiFi.status() != WL_CONNECTED)  
  {  
   delay(500);  
   Serial.print(".");  
  }  
  Serial.println("");  
  Serial.println("WiFi connected");  
  // Print the IP address  
  Serial.println(WiFi.localIP());  
  ThingSpeak.begin(client);  
 }  
 void loop()   
 {  
  static boolean data_state = false;  
  temperature = dht.readTemperature();  
  humidity = dht.readHumidity();  
  Serial.print("Temperature Value is :");  
  Serial.print(temperature);  
  Serial.println("C");  
  Serial.print("Humidity Value is :");  
  Serial.print(humidity);  
  Serial.println("%");  
  // Write to ThingSpeak. There are up to 8 fields in a channel, allowing you to store up to 8 different  
  // pieces of information in a channel. Here, we write to field 1.  
  if( data_state )  
  {  
   ThingSpeak.writeField(myChannelNumber, 1, temperature, myWriteAPIKey);  
   data_state = false;  
  }  
  else  
  {  
   ThingSpeak.writeField(myChannelNumber, 2, humidity, myWriteAPIKey);  
   data_state = true;  
  }  
  delay(30000); // ThingSpeak will only accept updates every 15 seconds.  
 }  `

**Comment by ConorMatthews** [comment]
sorry about it looking like that

**Comment by ConorMatthews** [comment]
its from here: [http://embeddedlaboratory.blogspot.co.uk/2016/10/posting-dht11-values-to-thingspeak.html](url)

**Comment by lorol** [comment]
@ConorMatthews , [your channel](https://api.thingspeak.com/channels/340776%20/feeds.json?api_key=P6MITCR982A3ML9D) is fed with data, which either field value is missing on each point. When field1 is OK, the other is null, and vice-versa.

```
66 |  
-- | --
created_at | "2017-10-05T21:45:45Z"
entry_id | 479
field1 | "11"
field2 | null
67 |  
created_at | "2017-10-05T21:46:03Z"
entry_id | 480
field1 | null
field2 | "74"
```

You can try https://github.com/squix78/esp8266-dht-thingspeak-logger project for feeding data.

**Comment by ConorMatthews** [comment]
@lorol Thanks so much

**Comment by ConorMatthews** [comment]
@lorol In the code that you linked to do I have to input my channel ID as I can't find it in the code.
Thanks

**Comment by ConorMatthews** [comment]
Thanks so much for your help @loral
